version: "3.7"

x-images:

  # Use latest image if available; else build it.
  &latest
  build: .
  image: suneku:latest

x-mounts:

  # Mount all repository files.
  - &code
    type: bind
    bind: {osxfs: delegated}
    source: .
    target: /home/suneku/code

  - &data
    type: volume
    source: data
    target: /home/suneku/data

  # Special mounts for Jupyter configuration.
  - &ipython ~/.ipython:/home/monty/.ipython
  - &jupyter ~/.jupyter:/home/monty/.jupyter

volumes:

  data:
    name: suneku_data

services:

  # Run an interactive shell: docker-compose run bash
  bash:
    << : *latest
    command: bash
    container_name: suneku_bash
    volumes: [*code,*data]

  # Start Jupyter server: docker-compose up jupyter
  jupyter:
    <<: *latest
    command: jupyter notebook --no-browser --ip=0.0.0.0
    container_name: suneku_jupyter
    ports: ["127.0.0.1:8888:8888"]
    volumes: [*code,*data,*ipython,*jupyter]
    working_dir: /home/monty/suneku

  # Test new code: docker-compose run tests
  pytest:
    <<: *latest
    command: pytest suneku
    container_name: suneku_pytest
    volumes: [*code,*data]

