version: "3.7"

x-images:

  # Use latest image if available; else build it.
  &latest
  build: .
  image: suneku:latest

x-mounts:

  # Mount all repository files.
  - &repo
    bind: {osxfs: delegated}
    source: .
    target: /home/monty/suneku
    type: bind

  # Special mounts for Jupyter configuration.
  - &ipython ~/.ipython:/home/monty/.ipython
  - &jupyter ~/.jupyter:/home/monty/.jupyter

services:

  # Run an interactive shell: docker-compose run bash
  bash:
    << : *latest
    command: bash
    container_name: suneku-bash
    volumes: [*repo]

  # Start Jupyter server: docker-compose up jupyter
  jupyter:
    <<: *latest
    command: jupyter notebook --no-browser --ip=0.0.0.0
    container_name: suneku-jupyter
    ports: ["127.0.0.1:8888:8888"]
    volumes: [*repo,*ipython,*jupyter]
    working_dir: /home/monty/suneku

  # Test new code: docker-compose run tests
  pytest:
    <<: *latest
    command: pytest suneku
    container_name: suneku-pytest
    volumes: [*repo]
