version: "3.7"

x-images:

  # Use latest image if available; else build it.
  &latest
  build: .
  image: suneku:latest

x-mounts:

  # Entire repository (including hidden files!) -> ~/suneku
  - &repo .:/home/kingofsnake/suneku

  # Jupyter settings -> ~/.jupyter
  - &jupyter ./custom/.jupyter:/home/kingofsnake/.jupyter

services:

  # Run an interactive shell: docker-compose run bash
  bash:
    << : *latest
    command: bash
    container_name: suneku-bash
    volumes: [*repo]

  # Start Jupyter server: docker-compose up jupyter
  jupyter:
    <<: *latest
    command: jupyter notebook --no-browser --ip=0.0.0.0
    container_name: suneku-jupyter
    ports: ["127.0.0.1:8888:8888"]
    volumes: [*repo,*jupyter]
    working_dir: /home/kingofsnake/suneku/examples

  # Test freshly-baked code: docker-compose run tests
  tests:
    <<: *latest
    command: python suneku/tests/hello.py
    container_name: suneku-tests
