#!/usr/bin/env bash

# Build (or just update) a suneku_lab and start it.
# Remember to set JUPYTER_PASSWORD in your .env file!
# INPUTS
#   optional name of container (default 'suneku_lab')

CONTAINER_NAME=${1:-suneku_lab}
VERSION="latest"
IMAGE_NAME="suneku_lab:$VERSION"
DOCKERFILE_FOLDER="$HOME/suneku/labs/$VERSION/"
ENV_FILE="$HOME/suneku/.env"

# Build Docker image
docker build --tag $IMAGE_NAME $DOCKERFILE_FOLDER

# Run a new container in "detached" mode.
# Mount host machine's ~/suneku/ folder as /suneku/ in the container.
# Import credentials as environment variables from your .env file.
# Expose ports on your local server for the Jupyter server to use.
# Make /suneku/ the working directory.
# Run the suneku Jupyter launch script.
docker run \
    --detach \
    --name $CONTAINER_NAME \
    --volume "$HOME/suneku/:/suneku/" \
    --env-file $ENV_FILE \
    --publish 8888:8888 \
    --workdir "/suneku/" \
    $IMAGE_NAME \
    /suneku/labs/start_jupyter
    