#!/usr/bin/env bash

# Show existing images, networks, and containers.

bigprint() { printf "\n---------- $1 ----------\n"; }

bigprint 'Images'; docker images
bigprint 'Volumes'; docker volume ls
bigprint 'Networks'; docker network ls
bigprint 'Containers'; docker ps --all
printf '\n'
