#!/usr/bin/env bash

# Tell Docker to build and run a suneku lab.
# INPUTS
#   optional name of container (default 'my_suneku_lab')


CONTAINER_NAME=${1:-suneku_lab}
SUNEKU_FOLDER="$HOME/suneku/"
ENV_FILE="$SUNEKU_FOLDER.env"

# Build Docker image (if it's already built, this will update it)
docker build --tag suneku_lab:latest "$SUNEKU_FOLDER/labs/latest"

# Run a new container in "detached" mode.
# Mount host machine's ~/suneku/ folder as /suneku/ in the container.
# Import environment variables from host's ~/suneku/.env file.
# Expose ports the Jupyter server will use.
# Make /suneku/ the working directory.
docker run \
    --detach \
    --name $CONTAINER_NAME \
    --volume $SUNEKU_FOLDER:/suneku/ \
    --env-file $ENV_FILE \
    --publish 8888:8888 \
    --workdir="/suneku" \
    suneku_lab:latest
