#!/usr/bin/env bash
# Edit the Jupyter config file to use a password.
# (The password is whatever you set for JUPYTER_PASSWORD in your .env file.)
# Start a Jupyter server. Tell it where to find the config file.

JUPYTER_CONFIG_FILE="/suneku/labs/jupyter_notebook_config.py"
CONFIG_EDITING_SCRIPT="/suneku/labs/set_password.py"

# Set password in config file
python $CONFIG_EDITING_SCRIPT $JUPYTER_CONFIG_FILE
STATUS=$?

# Start Jupyter server
jupyter notebook --config=$JUPYTER_CONFIG_FILE

exit $STATUS